config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  resources :locations
  resources :mail_items

  root 'users#index'
  get 'users/locations' => 'index#locations', :as => :place
  get 'locations/:id', to:'locations#show'
  get 'mail_items/:id', to:'mail_items#show'
  get 'users/:id', to:'users#show'

end

app/models/location.rb
class Location < ActiveRecord::Base
	#association 
	belongs_to :mail_item

	#validations
	validates_presence_of :latitude
	validates_presence_of :longitude

	#scopes
end

app/models/mail_item.rb
class MailItem < ActiveRecord::Base
	
	#association 
	has_one :location
	belongs_to :user

	#validations
	validates_presence_of :date_arrived_pittsburgh
	validates_presence_of :shipping_weight
	validates_presence_of :sender

	#scopes
	#d
	scope :arrivedinqatar, lambda { where("date_arrived_qatar < ?" , Date.today) }
	
	#c (given 3 days to ship out of pittsburgh)
	scope :shippedout, lambda { where("date_arrived_pittsburgh < ?" , Date.today+3)}

	#e that there is a date in the date delivered field
	scope :delivered, lambda { where("date_delivered < ?" , Date.today) }
	

	#f to view all history but by order of sender for ease
	scope :shippedallInfo, lambda { where("date_arrived_pittsburgh < ?" , Date.today+3)}
	
	#b order by arrival date to pittsburgh if it is after todays date (alreadt arrived)
	scope :shippedout, lambda { where("date_arrived_pittsburgh < ?" , Date.today)}



end

app/models/user.rb
class User < ActiveRecord::Base
	#association 
	has_many :mail_item

	#validations
	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :andrew_id
	validates_presence_of :username
	validates_presence_of :password
	validates_presence_of :facilities

	#scopes

	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @locations =Location.find(params[:id])
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :mail_item_id)
    end
end

app/controllers/mail_items_controller.rb
class MailItemsController < ApplicationController
  before_action :set_mail_item, only: [:show, :edit, :update, :destroy]

  # GET /mail_items
  # GET /mail_items.json
  def index
    @mail_items = MailItem.all
  end

  # GET /mail_items/1
  # GET /mail_items/1.json
  def show
    @mail_items =MailItem.find(params[:id])
  end

  # GET /mail_items/new
  def new
    @mail_item = MailItem.new
  end

  # GET /mail_items/1/edit
  def edit
    @mail_items =MailItem.find(params[:id])
  end

  # POST /mail_items
  # POST /mail_items.json
  def create
    @mail_item = MailItem.new(mail_item_params)

    respond_to do |format|
      if @mail_item.save
        format.html { redirect_to @mail_item, notice: 'Mail item was successfully created.' }
        format.json { render :show, status: :created, location: @mail_item }
      else
        format.html { render :new }
        format.json { render json: @mail_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_items/1
  # PATCH/PUT /mail_items/1.json
  def update
    respond_to do |format|
      if @mail_item.update(mail_item_params)
        format.html { redirect_to @mail_item, notice: 'Mail item was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_item }
      else
        format.html { render :edit }
        format.json { render json: @mail_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_items/1
  # DELETE /mail_items/1.json
  def destroy
    @mail_item.destroy
    respond_to do |format|
      format.html { redirect_to mail_items_url, notice: 'Mail item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_item
      @mail_item = MailItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_item_params
      params.require(:mail_item).permit(:date_arrived_pittsburgh, :date_arrived_qatar, :date_delivered, :sender, :description, :comment, :shipping_weight, :discard, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user=User.new
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user =User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user =User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :andrew_id, :username, :password, :facilities)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/mail_items_helper.rb
module MailItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :mail_item_id %><br>
    <%= f.number_field :mail_item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Mail item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.mail_item_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Mail item:</strong>
  <%= @location.mail_item_id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/mail_items/_form.html.erb
<%= form_for(@mail_item) do |f| %>
  <% if @mail_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mail_item.errors.count, "error") %> prohibited this mail_item from being saved:</h2>

      <ul>
      <% @mail_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_arrived_pittsburgh %><br>
    <%= f.date_select :date_arrived_pittsburgh %>
  </div>
  <div class="field">
    <%= f.label :date_arrived_qatar %><br>
    <%= f.date_select :date_arrived_qatar %>
  </div>
  <div class="field">
    <%= f.label :date_delivered %><br>
    <%= f.date_select :date_delivered %>
  </div>
  <div class="field">
    <%= f.label :sender %><br>
    <%= f.text_field :sender %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :shipping_weight %><br>
    <%= f.number_field :shipping_weight %>
  </div>
  <div class="field">
    <%= f.label :discard %><br>
    <%= f.text_field :discard %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_items/edit.html.erb
<h1>Editing Mail Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @mail_item %> |
<%= link_to 'Back', mail_items_path %>

app/views/mail_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mail Items</h1>

<table>
  <thead>
    <tr>
      <th>Date arrived pittsburgh</th>
      <th>Date arrived qatar</th>
      <th>Date delivered</th>
      <th>Sender</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Shipping weight</th>
      <th>Discard</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_items.each do |mail_item| %>
      <tr>
        <td><%= mail_item.date_arrived_pittsburgh %></td>
        <td><%= mail_item.date_arrived_qatar %></td>
        <td><%= mail_item.date_delivered %></td>
        <td><%= mail_item.sender %></td>
        <td><%= mail_item.description %></td>
        <td><%= mail_item.comment %></td>
        <td><%= mail_item.shipping_weight %></td>
        <td><%= mail_item.discard %></td>
        <td><%= mail_item.user_id %></td>
        <td><%= link_to 'Show', mail_item %></td>
        <td><%= link_to 'Edit', edit_mail_item_path(mail_item) %></td>
        <td><%= link_to 'Destroy', mail_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mail item', new_mail_item_path %>

app/views/mail_items/new.html.erb
<h1>New Mail Item</h1>

<%= render 'form' %>

<%= link_to 'Back', mail_items_path %>

app/views/mail_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date arrived pittsburgh:</strong>
  <%= @mail_item.date_arrived_pittsburgh %>
</p>

<p>
  <strong>Date arrived qatar:</strong>
  <%= @mail_item.date_arrived_qatar %>
</p>

<p>
  <strong>Date delivered:</strong>
  <%= @mail_item.date_delivered %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @mail_item.sender %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mail_item.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @mail_item.comment %>
</p>

<p>
  <strong>Shipping weight:</strong>
  <%= @mail_item.shipping_weight %>
</p>

<p>
  <strong>Discard:</strong>
  <%= @mail_item.discard %>
</p>

<p>
  <strong>User:</strong>
  <%= @mail_item.user_id %>
</p>

<%= link_to 'Edit', edit_mail_item_path(@mail_item) %> |
<%= link_to 'Back', mail_items_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :andrew_id %><br>
    <%= f.text_field :andrew_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :facilities %><br>
    <%= f.text_field :facilities %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Andrew</th>
      <th>Username</th>
      <th>Password</th>
      <th>Facilities</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.andrew_id %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.facilities %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Andrew:</strong>
  <%= @user.andrew_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Facilities:</strong>
  <%= @user.facilities %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>